version: "3.8"

services:
  mongo:
    container_name: mongo
    restart: always
    image: mongo
    ports:
    - "27017:27017"


  app:
    build: .
    command: yarn start
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
    links:
      - mongo
    depends_on:
      - mongo


